#!/bin/bash

app=$(cat ~/.config/zenlauncher/applist.csv | sed 's/,/\n/g' | sed 's/^ *\(.*\) *$/\1/g' | zenity --list --title="ZenLauncher" --column="Command" --column="Description" --column="Command" --print-column=3 --width=500 --height=300)
eval $app
